typescript:
  - any:
      - '**/*.ts'
      - '**/*.tsx'

testing:
  - any:
      - 'tests/**/*'
      - '**/*.test.ts'
      - '**/*.test.tsx'
      - '**/*.spec.ts'
      - '**/*.spec.tsx'

github-actions:
  - any:
      - '.github/workflows/**/*'
      - '.github/actions/**/*'

documentation:
  - any:
      - '**/*.md'
      - 'docs/**/*'
      - 'LICENSE'
