# PR 自动标记配置
# 根据修改的文件路径自动为 PR 添加相应标签

typescript:
  - '**/*.ts'
  - '**/*.tsx'

testing:
  - 'tests/**/*'
  - '**/*.test.ts'
  - '**/*.test.tsx'
  - '**/*.spec.ts'
  - '**/*.spec.tsx'

github-actions:
  - '.github/workflows/**/*'
  - '.github/actions/**/*'

documentation:
  - '**/*.md'
  - 'docs/**/*'
  - 'LICENSE'
