sonar.projectKey=LX-Addons_Cookie_Manager_Pro
sonar.organization=lx-addons
sonar.projectName=Cookie Manager Pro

sonar.sources=src
sonar.tests=tests
sonar.sourceEncoding=UTF-8

sonar.exclusions=**/node_modules/**,**/build/**,**/dist/**,**/coverage/**,**/.wxt/**,**/playwright-report/**,**/.output/**

sonar.test.exclusions=**/*.test.ts,**/*.test.tsx,**/*.spec.ts,**/*.spec.tsx

sonar.cpd.exclusions=**/*.test.ts,**/*.test.tsx,**/*.spec.ts,**/*.spec.tsx

sonar.scm.provider=git
