// Generated by wxt
export {}
declare global {
  const CheckboxGroup: typeof import('D:/trea-cn/Cookie_Manager_Pro/components/CheckboxGroup').CheckboxGroup
  const ClearLog: typeof import('D:/trea-cn/Cookie_Manager_Pro/components/ClearLog').ClearLog
  const ConfirmDialog: typeof import('D:/trea-cn/Cookie_Manager_Pro/components/ConfirmDialog').ConfirmDialog
  const ConfirmDialogWrapper: typeof import('D:/trea-cn/Cookie_Manager_Pro/components/ConfirmDialogWrapper').ConfirmDialogWrapper
  const ContentScriptContext: typeof import('wxt/utils/content-script-context').ContentScriptContext
  const CookieEditor: typeof import('D:/trea-cn/Cookie_Manager_Pro/components/CookieEditor').CookieEditor
  const CookieList: typeof import('D:/trea-cn/Cookie_Manager_Pro/components/CookieList').CookieList
  const CookieListContent: typeof import('D:/trea-cn/Cookie_Manager_Pro/components/CookieList').CookieListContent
  const DomainManager: typeof import('D:/trea-cn/Cookie_Manager_Pro/components/DomainManager').DomainManager
  const ErrorBoundary: typeof import('D:/trea-cn/Cookie_Manager_Pro/components/ErrorBoundary').ErrorBoundary
  const InvalidMatchPattern: typeof import('wxt/utils/match-patterns').InvalidMatchPattern
  const MatchPattern: typeof import('wxt/utils/match-patterns').MatchPattern
  const RadioGroup: typeof import('D:/trea-cn/Cookie_Manager_Pro/components/RadioGroup').RadioGroup
  const Settings: typeof import('D:/trea-cn/Cookie_Manager_Pro/components/Settings').Settings
  const assessCookieRisk: typeof import('D:/trea-cn/Cookie_Manager_Pro/utils/index').assessCookieRisk
  const browser: typeof import('wxt/browser').browser
  const buildOrigins: typeof import('D:/trea-cn/Cookie_Manager_Pro/utils/index').buildOrigins
  const cleanupExpiredCookies: typeof import('D:/trea-cn/Cookie_Manager_Pro/utils/cleanup').cleanupExpiredCookies
  const clearBrowserData: typeof import('D:/trea-cn/Cookie_Manager_Pro/utils/index').clearBrowserData
  const clearCookies: typeof import('D:/trea-cn/Cookie_Manager_Pro/utils/index').clearCookies
  const clearSingleCookie: typeof import('D:/trea-cn/Cookie_Manager_Pro/utils/index').clearSingleCookie
  const createIframeUi: typeof import('wxt/utils/content-script-ui/iframe').createIframeUi
  const createIntegratedUi: typeof import('wxt/utils/content-script-ui/integrated').createIntegratedUi
  const createShadowRootUi: typeof import('wxt/utils/content-script-ui/shadow-root').createShadowRootUi
  const defineAppConfig: typeof import('wxt/utils/define-app-config').defineAppConfig
  const defineBackground: typeof import('wxt/utils/define-background').defineBackground
  const defineContentScript: typeof import('wxt/utils/define-content-script').defineContentScript
  const defineUnlistedScript: typeof import('wxt/utils/define-unlisted-script').defineUnlistedScript
  const defineWxtPlugin: typeof import('wxt/utils/define-wxt-plugin').defineWxtPlugin
  const editCookie: typeof import('D:/trea-cn/Cookie_Manager_Pro/utils/index').editCookie
  const fakeBrowser: typeof import('wxt/testing').fakeBrowser
  const formatLogTime: typeof import('D:/trea-cn/Cookie_Manager_Pro/utils/index').formatLogTime
  const getActionColor: typeof import('D:/trea-cn/Cookie_Manager_Pro/utils/index').getActionColor
  const getActionText: typeof import('D:/trea-cn/Cookie_Manager_Pro/utils/index').getActionText
  const getCookieKey: typeof import('D:/trea-cn/Cookie_Manager_Pro/utils/index').getCookieKey
  const getCookieTypeName: typeof import('D:/trea-cn/Cookie_Manager_Pro/utils/index').getCookieTypeName
  const getRiskLevelColor: typeof import('D:/trea-cn/Cookie_Manager_Pro/utils/index').getRiskLevelColor
  const getRiskLevelText: typeof import('D:/trea-cn/Cookie_Manager_Pro/utils/index').getRiskLevelText
  const injectScript: typeof import('wxt/utils/inject-script').injectScript
  const isDomainMatch: typeof import('D:/trea-cn/Cookie_Manager_Pro/utils/index').isDomainMatch
  const isInList: typeof import('D:/trea-cn/Cookie_Manager_Pro/utils/index').isInList
  const isSensitiveCookie: typeof import('D:/trea-cn/Cookie_Manager_Pro/utils/index').isSensitiveCookie
  const isThirdPartyCookie: typeof import('D:/trea-cn/Cookie_Manager_Pro/utils/index').isThirdPartyCookie
  const isTrackingCookie: typeof import('D:/trea-cn/Cookie_Manager_Pro/utils/index').isTrackingCookie
  const maskCookieValue: typeof import('D:/trea-cn/Cookie_Manager_Pro/utils/index').maskCookieValue
  const normalizeDomain: typeof import('D:/trea-cn/Cookie_Manager_Pro/utils/index').normalizeDomain
  const performCleanup: typeof import('D:/trea-cn/Cookie_Manager_Pro/utils/cleanup').performCleanup
  const performCleanupWithFilter: typeof import('D:/trea-cn/Cookie_Manager_Pro/utils/cleanup').performCleanupWithFilter
  const storage: typeof import('wxt/utils/storage').storage
  const toggleSetValue: typeof import('D:/trea-cn/Cookie_Manager_Pro/utils/index').toggleSetValue
  const useAppConfig: typeof import('wxt/utils/app-config').useAppConfig
  const useCallback: typeof import('react').useCallback
  const useConfirmDialog: typeof import('D:/trea-cn/Cookie_Manager_Pro/hooks/useConfirmDialog').useConfirmDialog
  const useContext: typeof import('react').useContext
  const useEffect: typeof import('react').useEffect
  const useMemo: typeof import('react').useMemo
  const useReducer: typeof import('react').useReducer
  const useRef: typeof import('react').useRef
  const useState: typeof import('react').useState
  const useStorage: typeof import('D:/trea-cn/Cookie_Manager_Pro/hooks/useStorage').useStorage
  const useTranslation: typeof import('D:/trea-cn/Cookie_Manager_Pro/hooks/useTranslation').useTranslation
  const validateDomain: typeof import('D:/trea-cn/Cookie_Manager_Pro/utils/index').validateDomain
}
// for type re-export
declare global {
  // @ts-ignore
  export type { Browser } from 'wxt/browser'
  import('wxt/browser')
  // @ts-ignore
  export type { StorageArea, WxtStorage, WxtStorageItem, StorageItemKey, StorageAreaChanges, MigrationError } from 'wxt/utils/storage'
  import('wxt/utils/storage')
  // @ts-ignore
  export type { WxtWindowEventMap } from 'wxt/utils/content-script-context'
  import('wxt/utils/content-script-context')
  // @ts-ignore
  export type { IframeContentScriptUi, IframeContentScriptUiOptions } from 'wxt/utils/content-script-ui/iframe'
  import('wxt/utils/content-script-ui/iframe')
  // @ts-ignore
  export type { IntegratedContentScriptUi, IntegratedContentScriptUiOptions } from 'wxt/utils/content-script-ui/integrated'
  import('wxt/utils/content-script-ui/integrated')
  // @ts-ignore
  export type { ShadowRootContentScriptUi, ShadowRootContentScriptUiOptions } from 'wxt/utils/content-script-ui/shadow-root'
  import('wxt/utils/content-script-ui/shadow-root')
  // @ts-ignore
  export type { ContentScriptUi, ContentScriptUiOptions, ContentScriptOverlayAlignment, ContentScriptAppendMode, ContentScriptInlinePositioningOptions, ContentScriptOverlayPositioningOptions, ContentScriptModalPositioningOptions, ContentScriptPositioningOptions, ContentScriptAnchoredOptions, AutoMountOptions, StopAutoMount, AutoMount } from 'wxt/utils/content-script-ui/types'
  import('wxt/utils/content-script-ui/types')
  // @ts-ignore
  export type { WxtAppConfig } from 'wxt/utils/define-app-config'
  import('wxt/utils/define-app-config')
  // @ts-ignore
  export type { ScriptPublicPath, InjectScriptOptions } from 'wxt/utils/inject-script'
  import('wxt/utils/inject-script')
  // @ts-ignore
  export type { ShowConfirmFn } from 'D:/trea-cn/Cookie_Manager_Pro/components/ConfirmDialogWrapper'
  import('D:/trea-cn/Cookie_Manager_Pro/components/ConfirmDialogWrapper')
  // @ts-ignore
  export type { ErrorBoundary } from 'D:/trea-cn/Cookie_Manager_Pro/components/ErrorBoundary'
  import('D:/trea-cn/Cookie_Manager_Pro/components/ErrorBoundary')
  // @ts-ignore
  export type { CleanupOptions, CleanupResult } from 'D:/trea-cn/Cookie_Manager_Pro/utils/cleanup'
  import('D:/trea-cn/Cookie_Manager_Pro/utils/cleanup')
  // @ts-ignore
  export type { ClearBrowserDataOptions, ClearCookiesOptions } from 'D:/trea-cn/Cookie_Manager_Pro/utils/index'
  import('D:/trea-cn/Cookie_Manager_Pro/utils/index')
}
