// Generated by wxt
export {}
declare global {
  const CheckboxGroup: typeof import('D:/trea-cn/Cookie_Manager_Pro/components/CheckboxGroup')['CheckboxGroup']
  const ClearLog: typeof import('D:/trea-cn/Cookie_Manager_Pro/components/ClearLog')['ClearLog']
  const ConfirmDialog: typeof import('D:/trea-cn/Cookie_Manager_Pro/components/ConfirmDialog')['ConfirmDialog']
  const ConfirmDialogWrapper: typeof import('D:/trea-cn/Cookie_Manager_Pro/components/ConfirmDialogWrapper')['ConfirmDialogWrapper']
  const ContentScriptContext: typeof import('wxt/client')['ContentScriptContext']
  const CookieEditor: typeof import('D:/trea-cn/Cookie_Manager_Pro/components/CookieEditor')['CookieEditor']
  const CookieList: typeof import('D:/trea-cn/Cookie_Manager_Pro/components/CookieList')['CookieList']
  const CookieListContent: typeof import('D:/trea-cn/Cookie_Manager_Pro/components/CookieList')['CookieListContent']
  const DomainManager: typeof import('D:/trea-cn/Cookie_Manager_Pro/components/DomainManager')['DomainManager']
  const ErrorBoundary: typeof import('D:/trea-cn/Cookie_Manager_Pro/components/ErrorBoundary')['ErrorBoundary']
  const InvalidMatchPattern: typeof import('wxt/sandbox')['InvalidMatchPattern']
  const MatchPattern: typeof import('wxt/sandbox')['MatchPattern']
  const MigrationError: typeof import('wxt/storage')['MigrationError']
  const RadioGroup: typeof import('D:/trea-cn/Cookie_Manager_Pro/components/RadioGroup')['RadioGroup']
  const Settings: typeof import('D:/trea-cn/Cookie_Manager_Pro/components/Settings')['Settings']
  const assessCookieRisk: typeof import('D:/trea-cn/Cookie_Manager_Pro/utils/index')['assessCookieRisk']
  const browser: typeof import('wxt/browser')['browser']
  const buildOrigins: typeof import('D:/trea-cn/Cookie_Manager_Pro/utils/index')['buildOrigins']
  const cleanupExpiredCookies: typeof import('D:/trea-cn/Cookie_Manager_Pro/utils/cleanup')['cleanupExpiredCookies']
  const clearBrowserData: typeof import('D:/trea-cn/Cookie_Manager_Pro/utils/index')['clearBrowserData']
  const clearCookies: typeof import('D:/trea-cn/Cookie_Manager_Pro/utils/index')['clearCookies']
  const clearSingleCookie: typeof import('D:/trea-cn/Cookie_Manager_Pro/utils/index')['clearSingleCookie']
  const createIframeUi: typeof import('wxt/client')['createIframeUi']
  const createIntegratedUi: typeof import('wxt/client')['createIntegratedUi']
  const createShadowRootUi: typeof import('wxt/client')['createShadowRootUi']
  const defineAppConfig: typeof import('wxt/sandbox')['defineAppConfig']
  const defineBackground: typeof import('wxt/sandbox')['defineBackground']
  const defineConfig: typeof import('wxt')['defineConfig']
  const defineContentScript: typeof import('wxt/sandbox')['defineContentScript']
  const defineUnlistedScript: typeof import('wxt/sandbox')['defineUnlistedScript']
  const defineWxtPlugin: typeof import('wxt/sandbox')['defineWxtPlugin']
  const editCookie: typeof import('D:/trea-cn/Cookie_Manager_Pro/utils/index')['editCookie']
  const fakeBrowser: typeof import('wxt/testing')['fakeBrowser']
  const formatLogTime: typeof import('D:/trea-cn/Cookie_Manager_Pro/utils/index')['formatLogTime']
  const getActionColor: typeof import('D:/trea-cn/Cookie_Manager_Pro/utils/index')['getActionColor']
  const getActionText: typeof import('D:/trea-cn/Cookie_Manager_Pro/utils/index')['getActionText']
  const getCookieKey: typeof import('D:/trea-cn/Cookie_Manager_Pro/utils/index')['getCookieKey']
  const getCookieTypeName: typeof import('D:/trea-cn/Cookie_Manager_Pro/utils/index')['getCookieTypeName']
  const getRiskLevelColor: typeof import('D:/trea-cn/Cookie_Manager_Pro/utils/index')['getRiskLevelColor']
  const getRiskLevelText: typeof import('D:/trea-cn/Cookie_Manager_Pro/utils/index')['getRiskLevelText']
  const injectScript: typeof import('wxt/client')['injectScript']
  const isDomainMatch: typeof import('D:/trea-cn/Cookie_Manager_Pro/utils/index')['isDomainMatch']
  const isInList: typeof import('D:/trea-cn/Cookie_Manager_Pro/utils/index')['isInList']
  const isSensitiveCookie: typeof import('D:/trea-cn/Cookie_Manager_Pro/utils/index')['isSensitiveCookie']
  const isThirdPartyCookie: typeof import('D:/trea-cn/Cookie_Manager_Pro/utils/index')['isThirdPartyCookie']
  const isTrackingCookie: typeof import('D:/trea-cn/Cookie_Manager_Pro/utils/index')['isTrackingCookie']
  const maskCookieValue: typeof import('D:/trea-cn/Cookie_Manager_Pro/utils/index')['maskCookieValue']
  const normalizeDomain: typeof import('D:/trea-cn/Cookie_Manager_Pro/utils/index')['normalizeDomain']
  const performCleanup: typeof import('D:/trea-cn/Cookie_Manager_Pro/utils/cleanup')['performCleanup']
  const performCleanupWithFilter: typeof import('D:/trea-cn/Cookie_Manager_Pro/utils/cleanup')['performCleanupWithFilter']
  const storage: typeof import('wxt/storage')['storage']
  const toggleSetValue: typeof import('D:/trea-cn/Cookie_Manager_Pro/utils/index')['toggleSetValue']
  const useAppConfig: typeof import('wxt/client')['useAppConfig']
  const useCallback: typeof import('react')['useCallback']
  const useConfirmDialog: typeof import('D:/trea-cn/Cookie_Manager_Pro/hooks/useConfirmDialog')['useConfirmDialog']
  const useContext: typeof import('react')['useContext']
  const useEffect: typeof import('react')['useEffect']
  const useMemo: typeof import('react')['useMemo']
  const useReducer: typeof import('react')['useReducer']
  const useRef: typeof import('react')['useRef']
  const useState: typeof import('react')['useState']
  const useStorage: typeof import('D:/trea-cn/Cookie_Manager_Pro/hooks/useStorage')['useStorage']
  const useTranslation: typeof import('D:/trea-cn/Cookie_Manager_Pro/hooks/useTranslation')['useTranslation']
  const validateDomain: typeof import('D:/trea-cn/Cookie_Manager_Pro/utils/index')['validateDomain']
}
// for type re-export
declare global {
  // @ts-ignore
  export type { ShowConfirmFn } from 'D:/trea-cn/Cookie_Manager_Pro/components/ConfirmDialogWrapper'
  import('D:/trea-cn/Cookie_Manager_Pro/components/ConfirmDialogWrapper')
  // @ts-ignore
  export type { ErrorBoundary } from 'D:/trea-cn/Cookie_Manager_Pro/components/ErrorBoundary'
  import('D:/trea-cn/Cookie_Manager_Pro/components/ErrorBoundary')
  // @ts-ignore
  export type { CleanupOptions, CleanupResult } from 'D:/trea-cn/Cookie_Manager_Pro/utils/cleanup'
  import('D:/trea-cn/Cookie_Manager_Pro/utils/cleanup')
  // @ts-ignore
  export type { ClearBrowserDataOptions, ClearCookiesOptions } from 'D:/trea-cn/Cookie_Manager_Pro/utils/index'
  import('D:/trea-cn/Cookie_Manager_Pro/utils/index')
}
